"""dirty bit for aggregates

Revision ID: 6c6941a9191f
Revises: a217bc54e23e
Create Date: 2022-10-24 15:40:21.284115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c6941a9191f"
down_revision = "a217bc54e23e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_key_owner", "aggregate_elements", ["key", "owner"], unique=False
    )

    op.add_column("aggregates", sa.Column("dirty", sa.Boolean(), nullable=True))
    op.execute("UPDATE aggregates SET dirty = false")
    op.alter_column("aggregates", "dirty", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aggregates", "dirty")
    op.drop_index("ix_key_owner", table_name="aggregate_elements")
    # ### end Alembic commands ###
