"""reception time

Revision ID: 97d21a85b8a8
Revises: 78dd67881db4
Create Date: 2022-10-25 11:28:12.349574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "97d21a85b8a8"
down_revision = "78dd67881db4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_status",
        sa.Column("reception_time", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.execute("UPDATE message_status SET reception_time = to_timestamp(1666683834.0)")
    op.alter_column("message_status", "reception_time", nullable=False)

    op.add_column(
        "pending_messages",
        sa.Column("reception_time", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.execute("UPDATE pending_messages SET reception_time = to_timestamp(1666683834.0)")
    op.alter_column("pending_messages", "reception_time", nullable=False)

    op.add_column(
        "rejected_messages",
        sa.Column("message", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.alter_column(
        "rejected_messages", "traceback", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rejected_messages", "traceback", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("rejected_messages", "message")
    op.drop_column("message_status", "reception_time")
    op.drop_column("pending_messages", "reception_time")
    # ### end Alembic commands ###
