# Starts all the services used by pyaleph, minus pyaleph itself. This is used for local development.
# Use the docker-compose/docker-compose.yml file for deployment.

version: '2.2'

volumes:
  pyaleph-ipfs:
  pyaleph-mongodb:

services:

  rabbitmq:
    restart: always
    image: rabbitmq:3.10.7-management
    networks:
      - pyaleph
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  p2p-service:
    restart: always
    image: alephim/p2p-service:0.1.1
    networks:
      - pyaleph
    volumes:
      - ../../config.yml:/etc/p2p-service/config.yml
      - ../../keys/node-secret.pkcs8.der:/etc/p2p-service/node-secret.pkcs8.der
    depends_on:
      - rabbitmq
    environment:
      RUST_LOG: info
    ports:
      - "4025:4025"
      - "127.0.0.1:4030:4030"
    command:
      - "--config"
      - "/etc/p2p-service/config.yml"
      - "--private-key-file"
      - "/etc/p2p-service/node-secret.pkcs8.der"

  ipfs:
    restart: always
    image: ipfs/kubo:v0.15.0
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
    volumes:
      - "pyaleph-ipfs:/data/ipfs"
    environment:
      - IPFS_PROFILE=server
    networks:
      - pyaleph
    command: ["daemon", "--enable-pubsub-experiment", "--migrate"]

  mongodb:
    restart: always
    image: mongo:4.4
    volumes:
      - pyaleph-mongodb:/data/db
    command: mongod --storageEngine wiredTiger
    networks:
      - pyaleph
    ports:
      - "127.0.0.1:27017:27017"

networks:
  pyaleph:
