# Starts all the services used by pyaleph, minus pyaleph itself. This is used for local development.
# Use the docker-compose/docker-compose.yml file for deployment.

version: '2.2'

volumes:
  pyaleph-ipfs:
  pyaleph-mongodb:

services:
  p2pd:
    restart: always
    image: alephim/jsp2pd:0.10.2-1.0.0
    networks:
      - pyaleph
    environment:
      PRIVATE_KEY_FILE: "/etc/jsp2pd/keys/serialized-node-secret.key"
      LISTEN_MADDR: "/ip4/0.0.0.0/tcp/4030"
      HOST_MADDRS: "/ip4/0.0.0.0/tcp/4025"
      PUBSUB: "true"
      PUBSUB_ROUTER: "floodsub"
    ports:
      - "4025:4025"
      - "4030:4030"
    volumes:
      - ../../keys:/etc/jsp2pd/keys

  ipfs:
    restart: always
    image: ipfs/go-ipfs:v0.12.1
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - "pyaleph-ipfs:/data/ipfs"
    environment:
      - IPFS_PROFILE=server
    networks:
      - pyaleph
    command: ["daemon", "--enable-pubsub-experiment", "--migrate"]

  mongodb:
    restart: always
    image: mongo:4.4
    volumes:
      - pyaleph-mongodb:/data/db
    command: mongod --storageEngine wiredTiger
    networks:
      - pyaleph
    ports:
      - "27017:27017"

networks:
  pyaleph:
