version: '2.2'

volumes:
  pyaleph-ipfs:
  pyaleph-mongodb:

services:
  pyaleph:
    restart: always
    image: alephim/pyaleph-node:v0.3.3
    command: --config /opt/pyaleph/config.yml --key-dir /opt/pyaleph/keys -v
    ports:
      - "127.0.0.1:8000:8000/tcp"
      - "4024:4024/tcp"
    volumes:
      - ./config.yml:/opt/pyaleph/config.yml
      - ./keys:/opt/pyaleph/keys
    depends_on:
      - mongodb
      - ipfs
      - p2p-service
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  p2p-service:
    restart: always
    image: alephim/p2p-service:0.1.1
    networks:
      - pyaleph
    volumes:
      - ./config.yml:/etc/p2p-service/config.yml
      - ./keys/node-secret.pkcs8.der:/etc/p2p-service/node-secret.pkcs8.der
    depends_on:
      - rabbitmq
    environment:
      RUST_LOG: info
    ports:
      - "4025:4025"
      - "127.0.0.1:4030:4030"
    command:
      - "--config"
      - "/etc/p2p-service/config.yml"
      - "--private-key-file"
      - "/etc/p2p-service/node-secret.pkcs8.der"

  rabbitmq:
    restart: always
    image: rabbitmq:3.10.7-management
    networks:
      - pyaleph
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  ipfs:
    restart: always
    image: ipfs/kubo:v0.15.0
    ports:
      - "4001:4001"
      - "4001:4001/udp"
    volumes:
      - "pyaleph-ipfs:/data/ipfs"
    environment:
      - IPFS_PROFILE=server
    networks:
      - pyaleph
    command: ["daemon", "--enable-pubsub-experiment", "--migrate"]

  mongodb:
    restart: always
    image: mongo:4.4
    volumes:
      - pyaleph-mongodb:/data/db
    command: mongod --storageEngine wiredTiger
    networks:
      - pyaleph

networks:
  pyaleph:
