# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyAleph

on:
  push:
    branches:
      - dev
      - master
      - od-mypy
  pull_request:
    branches:
      - dev
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch the whole history for all tags and branches (required for aleph.__version__)
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install .[testing]
    - name: Test git
      run: |
        git status
        git describe --tags
    - name: Check types
      run: |
        mypy src/
    - name: Run unit tests
      run: |
        pytest -v .

  build:
    runs-on: ubuntu-20.04
    needs: tests
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          git fetch --prune --unshallow --tags
          docker build . -t pyaleph-node:${GITHUB_REF##*/} -f deployment/docker-build/pyaleph.dockerfile # --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache
